services:
  app:
    build: .
    container_name: telegram-instagram-forwarder
    command: tail -F anything
    ports:
      - 80:80
      - 5678:5678
      - 3389:3389
      - 9222:9222
    volumes:
      - .:/code
