services:
  app:
    build:
      context: .
      shm_size: '1gb'
    shm_size: '1gb'
    privileged: true
    user: 'bot'
    container_name: telegram-instagram-forwarder
    ports:
      - 5900:5900
    volumes:
      - .:/code
